### ISSUE TITLE
Retrieving all Profiles

### ISSUE THREAD

**Issue by HLFH** [getyoti/yoti-ruby-sdk#13]
Hi,

I would like to retrieve all profiles using `yoti-ruby-sdk` but it seems your SDK does not allow to do that.
And the Yoti Dashboard does not offer *CSV export*. So I'm stuck with people having KYC'd with Yoti before we implemented the `yoti-ruby-sdk` solution: we have been able to retrieve new profiles, one-one-one with your SDK ; but being able to retrieve all profiles would definitely solve this issue, it is a nightmare with the Yoti Dashboard, at this moment. Can we have access to all the submitted profiles using `yoti-ruby-sdk`?

Thank you,
Gaspard

**Comment by vassyz** [comment]
Hi Gaspard

The SDK can be used to decode Yoti profiles. Unfortunately, at the moment, you can't use it to get a list of all profiles. As you mentioned in the query, you have to do it in a one-by-one approach: save the user details in the database every time you request a profile through the SDK.

Regards,
Sebastian

**Comment by HLFH** [comment]
Hi @vassyz, 

> As you mentioned in the query, you have to do it in a one-by-one approach: save the user details in the database every time you request a profile through the SDK.

Yes, I do that, and `yoti-ruby-sdk` is great, I've read your last commits, thank you.

But, I would say vulgarly, we are quite fucked for the previous Yoti profiles done before we implement `yoti-ruby-sdk`. Difficult to play with the Yoti Dashboard, and check them in a quick manner. We have data we can check very slowly.

Shall I close at _won't fix_? 
And I haven't heard any news about the CSV export feature, by Sam Hill.

**Comment by vassyz** [comment]
The Dashboard export feature is something we're looking into. Currently, we don't have a timeline for when this will be available. I will close this issue as it is not directly related to the Ruby SDK.
